title: 'category 2-3'
image: classroom_children_reading_book_with_teacher-1024x681-1680785581.jpg
main_category: academics
updated_by: 49a762b8-3af8-4fac-aea2-ccd3373185c3
updated_at: 1682315263
blueprint: category
